version: '3.8'

services:
  healthconnect_postgres:
    image: postgres:15
    container_name: healthconnect_postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - healthconnect_postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - healthconnect_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  healthconnect_redis:
    image: redis:7-alpine
    container_name: healthconnect_redis
    ports:
      - "6379:6379"
    volumes:
      - healthconnect_redis:/data
    networks:
      - healthconnect_network
    restart: unless-stopped
    healthcheck:  
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  healthconnect_postgres:
    external: true
  healthconnect_redis:
    external: true

networks:
  healthconnect_network:
    external: true